# Generated by Django 4.0.5 on 2022-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_faces', models.CharField(max_length=255)),
                ('emotions', models.CharField(max_length=500)),
            ],
        ),
    ]
