# Generated by Django 4.0.5 on 2022-07-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facialexpression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='face_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
