# Generated by Django 4.0.5 on 2022-07-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facialexpression', '0002_face_face_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_faces', models.CharField(max_length=255)),
            ],
        ),
    ]
